show user;

--workshop1_01번 문제
select DEPARTMENT_NAME as "학과 명", category as "계열"
from TB_DEPARTMENT;

--workshop1_02번 문제
select DEPARTMENT_NAME ||'의 정원은 '|| CAPACITY ||'명 입니다.' as "학과별 정원"
from TB_DEPARTMENT;

--workshop1_03번 문제
select STUDENT_NAME
from TB_STUDENT
where DEPARTMENT_NO = '001' and ABSENCE_YN = 'Y' and STUDENT_SSN like '%-2%' ;

--workshop1_04번 문제
select STUDENT_NAME
from TB_STUDENT
where STUDENT_NO in ('A513079','A513090','A513091','A513110','A513119');

--workshop1_05번 문제
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--workshop1_06번 문제
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
where DEPARTMENT_NO is null;

--workshop1_07번 문제
select STUDENT_NAME 
from TB_STUDENT
where DEPARTMENT_NO is null;

--workshop1_08번 문제
select CLASS_NO
from TB_CLASS
where PREATTENDING_CLASS_NO is not NULL;

--workshop1_09번 문제
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--workshop1_10번 문제
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ENTRANCE_DATE LIKE '02%' AND STUDENT_ADDRESS LIKE '%전주%' AND ABSENCE_YN = 'N';

--workshop2_01번 문제
select STUDENT_NO as "학번", STUDENT_NAME as "이름", TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') as "입학년도"
from tb_student
where DEPARTMENT_NO = '002'
order by 3;

--workshop2_02번 문제
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) !=3;

--workshop2_03번 문제
SELECT PROFESSOR_NAME AS "교수이름",TRUNC((SYSDATE - TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)))/365) + 1 AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1)='1';


--workshop2_04번 문제
SELECT SUBSTR(PROFESSOR_NAME,2) AS "이름"
FROM TB_PROFESSOR;

--workshop2_05번 문제
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6)))>19;

--workshop2_06번 문제
SELECT TO_CHAR(TO_DATE('2020/12/25'),'DAY')
FROM DUAL;

--workshop2_08번 문제
SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1)!='A';

--workshop2_09번 문제
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--workshop2_10번 문제
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--workshop2_11번 문제
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--workshop2_12번 문제
SELECT SUBSTR(TO_CHAR(TERM_NO),1,4)AS "년도",ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TO_CHAR(TERM_NO),1,4)
ORDER BY 1;

--workshop2_13번 문제
SELECT DEPARTMENT_NO, SUM(CASE WHEN ABSENCE_YN = 'Y' THEN 1
                           ELSE 0
                          END) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--workshop2_14번 문제
SELECT STUDENT_NAME AS "동일이름", COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >=2
ORDER BY 1;