show user;

--1번 문제
select DEPARTMENT_NAME as "학과 명", category as "계열"
from TB_DEPARTMENT;

--2번 문제
select DEPARTMENT_NAME ||'의 정원은 '|| CAPACITY ||'명 입니다.' as "학과별 정원"
from TB_DEPARTMENT;

--3번 문제
select STUDENT_NAME
from TB_STUDENT
where DEPARTMENT_NO = '001' and ABSENCE_YN = 'Y' and STUDENT_SSN like '%-2%' ;

--4번 문제
select STUDENT_NAME
from TB_STUDENT
where STUDENT_NO in ('A513079','A513090','A513091','A513110','A513119');

--5번 문제
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6번 문제
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
where DEPARTMENT_NO is null;

--7번 문제
select STUDENT_NAME 
from TB_STUDENT
where DEPARTMENT_NO is null;

--8번 문제
select CLASS_NO
from TB_CLASS
where PREATTENDING_CLASS_NO is not NULL;

--9번 문제
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--10번 문제
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ENTRANCE_DATE LIKE '02%' AND STUDENT_ADDRESS LIKE '%전주%' AND ABSENCE_YN = 'N';
